"""visit_table

Revision ID: aadb8a650083
Revises: e1e2b2e3c470
Create Date: 2023-06-26 05:37:50.800929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aadb8a650083'
down_revision = 'e1e2b2e3c470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visit_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], name=op.f('fk_visit_stat_book_id_book')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visit_stat_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_stat'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_stat')
    # ### end Alembic commands ###
